#!/bin/bash

./makeThemes.sh
./makeScripts.sh
./makeLibs.sh
echo '<!DOCTYPE html>' > index.htm
echo '<!-- Generated by make.sh -->' >> index.htm
echo '<html lang="en"><head>' >> index.htm
cat head.htm >> index.htm
echo '' >> index.htm
echo '<style>' >> index.htm
cat style.css >> index.htm
echo '' >> index.htm
echo '</style><link rel="stylesheet" type="text/css" href="/themes/game.css" id="themeCSS"></head><body class="background">' >> index.htm
cat body.htm >> index.htm
echo '' >> index.htm
echo '<script>' >> index.htm
cat script.js >> index.htm
echo '' >> index.htm
echo '</script></body></html>' >> index.htm

