#!/bin/bash

./makeThemes.sh
./makeScripts.sh
echo '<!DOCTYPE html>' > index.htm
echo '<!-- Generated by makeBig.sh -->' >> index.htm
echo '<html lang="en"><head>' >> index.htm
cat head.htm >> index.htm
echo '' >> index.htm
echo '<style>' >> index.htm
cat style.css >> index.htm
echo '' >> index.htm
echo '</style><style id="themeCSS">' >> index.htm
cat themes/default.css >> index.htm
echo '' >> index.htm
echo '</style></head><body class="background">' >> index.htm
cat body.htm >> index.htm
echo '' >> index.htm
echo '<script>' >> index.htm
cat script.js >> index.htm
echo '' >> index.htm
echo '</script></body></html>' >> index.htm

