#!/bin/bash

cd scripts

echo '// Generated by makeScripts.sh from the files in ./scripts/' > ../script.js
echo '' >> ../script.js
for f in *
do
  cat $f >> ../script.js
  echo '' >> ../script.js
done

cd ..
